refactor: data config
gosling-lang/gosling.js pull request #177
Opened 2021-02-04 16:22 UTC by wangqianwen0418

#161

2021-02-04 21:42 UTC, sehilyi commented
I am not sure if this is a draft or read to be reviewed. Can you assign me as a reviewer when your PR is ready?

2021-02-04 21:45 UTC, sehilyi commented
Also, FYI, you can put "Fix" in front of the issue number (i.e., "#161") if you feel the issue is addressed by this PR. The predefined string ("Fix") will automatically close the mapped issue(s) whenever this PR is merged to the master branch.

2021-02-04 22:30 UTC, wangqianwen0418 commented
sorry for the unclearness caused!
Yes, it is ready and please have a review

2021-02-05 00:08 UTC, sehilyi requested changes
Thank you for proposing and working on this! 

I think this is a way better than before in terms of the simplicity/readability (e.g., good to remove needless `tileset` strings).

I've left one suggestion on putting back a test. Other than that, it looks good to go.

2021-02-05 00:08 UTC, sehilyi commented on src/core/gosling.schema.ts
>      // !!! The below properties should be required ones since metadata determines the visualization type.
```suggestion
```

2021-02-05 00:08 UTC, sehilyi commented on src/core/gosling.schema.ts
> +    url: string;
Thank you for correcting this.

2021-02-05 00:08 UTC, sehilyi commented on src/core/utils/spec-preprocess.ts
>              // if `metadata` is not specified, we can not provide a correct template since we do not know the exact data type.
```suggestion
            // if `data` is not specified, we can not provide a correct template.
```

2021-02-05 00:08 UTC, sehilyi commented on src/gosling-track/gosling-track.ts
> +                                    return not ?? false
```suggestion
                                    return not
```

2021-02-05 00:08 UTC, sehilyi commented on src/gosling-track/gosling-track.ts
> +                                    return not ?? false
```suggestion
                                    return not
```

2021-02-05 00:08 UTC, sehilyi commented on src/gosling-track/gosling-track.ts
> +                                    return not ?? false
```suggestion
                                    return not
```

2021-02-05 00:08 UTC, sehilyi commented on src/core/utils/superpose.test.ts
>      });
```suggestion
    });
    it('superpose: [{}, { data }, { data }]', () => {	
        const spread = spreadTracksByData([	
            {	
                superpose: [	
                    {},	
                    { data: { type: 'csv', url: '' } },	
                    { data: { type: 'vector', url: '', column: 'c', value: 'p' } }	
                ]	
            }	
        ]);	
        expect(spread).toHaveLength(3);	
        expect('data' in spread[1]).toBe(true);	
        expect('data' in spread[2]).toBe(true);	
        expect(spread[1].superposeOnPreviousTrack).toBe(true); // Any spread tracks will have `superposeOnPreviousTrack` flags	
        expect(spread[2].superposeOnPreviousTrack).toBe(true); // Any spread tracks will have `superposeOnPreviousTrack` flags	
    });
```

I am not sure if this test is removed by mistake, but we shouldn't be removing tests.

2021-02-05 00:08 UTC, sehilyi commented on src/gosling-track/gosling-track.ts
> +                                    return not ?? false
I think this change is from your previous PR on the same branch.

2021-02-05 01:00 UTC, sehilyi approved these changes

2021-02-05 01:02 UTC, merged