feat: select example through url
gosling-lang/gosling.js pull request #367
Opened 2021-04-22 00:33 UTC by wangqianwen0418

select example through url for displaying examples in the static website

2021-04-22 15:45 UTC, sehilyi requested changes
Thank you for this update, this looks good! I just left one comment about preventing from showing an empty page when a given `id` does not exist.

Also, just curious how `id`s will be managed in the `gosling-website`. I guess we will be having a JSON array that stores example ids and other related information (e.g., thumbnail), and we just need to update the array to add/remove certain examples to show in the `gosling-website`?

2021-04-22 15:45 UTC, sehilyi commented on src/editor/editor.tsx
> +    const urlExampleIndex = urlParams?.example ? examples.map(d => d.id).indexOf(urlParams.example as string) : null;
Currently, when a wrong example id is used, the site becomes entirely empty. How about changing this part to show a default (e.g., first) example if `example` does not exist?

2021-04-22 16:28 UTC, wangqianwen0418 commented
Thanks! I have updated the code

2021-04-22 16:29 UTC, wangqianwen0418 commented
> I guess we will be having a JSON array that stores example ids and other related information (e.g., thumbnail), and we just need to update the array to add/remove certain examples to show in the gosling-website?
Yes, you are correct. The examples in gosling-website are currently documented in assets/example-list

2021-04-23 13:28 UTC, sehilyi approved these changes
Tested locally, and works well! I will merge this.

2021-04-23 13:28 UTC, merged